apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-intelligence-read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-intelligence-read
  template:
    metadata:
      labels:
        app: doc-intelligence-read
    spec:
      containers:
        - name: doc-intelligence-read
          image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/read-3.0
          env:
            - name: EULA
              value: "accept"
            - name: billing
              value: $BILLING_ENDPOINT
            - name: apiKey
              value: $API_KEY
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: doc-intelligence-read
spec:
  type: LoadBalancer
  selector:
    app: doc-intelligence-read
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
